/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the DatabaseCreateSchedulesMetadataSync type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseCreateSchedulesMetadataSync{}

// DatabaseCreateSchedulesMetadataSync struct for DatabaseCreateSchedulesMetadataSync
type DatabaseCreateSchedulesMetadataSync struct {
	ScheduleType *string `json:"schedule_type,omitempty"`
}

// NewDatabaseCreateSchedulesMetadataSync instantiates a new DatabaseCreateSchedulesMetadataSync object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseCreateSchedulesMetadataSync() *DatabaseCreateSchedulesMetadataSync {
	this := DatabaseCreateSchedulesMetadataSync{}
	return &this
}

// NewDatabaseCreateSchedulesMetadataSyncWithDefaults instantiates a new DatabaseCreateSchedulesMetadataSync object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseCreateSchedulesMetadataSyncWithDefaults() *DatabaseCreateSchedulesMetadataSync {
	this := DatabaseCreateSchedulesMetadataSync{}
	return &this
}

// GetScheduleType returns the ScheduleType field value if set, zero value otherwise.
func (o *DatabaseCreateSchedulesMetadataSync) GetScheduleType() string {
	if o == nil || IsNil(o.ScheduleType) {
		var ret string
		return ret
	}
	return *o.ScheduleType
}

// GetScheduleTypeOk returns a tuple with the ScheduleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseCreateSchedulesMetadataSync) GetScheduleTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduleType) {
		return nil, false
	}
	return o.ScheduleType, true
}

// HasScheduleType returns a boolean if a field has been set.
func (o *DatabaseCreateSchedulesMetadataSync) HasScheduleType() bool {
	if o != nil && !IsNil(o.ScheduleType) {
		return true
	}

	return false
}

// SetScheduleType gets a reference to the given string and assigns it to the ScheduleType field.
func (o *DatabaseCreateSchedulesMetadataSync) SetScheduleType(v string) {
	o.ScheduleType = &v
}

func (o DatabaseCreateSchedulesMetadataSync) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseCreateSchedulesMetadataSync) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScheduleType) {
		toSerialize["schedule_type"] = o.ScheduleType
	}
	return toSerialize, nil
}

type NullableDatabaseCreateSchedulesMetadataSync struct {
	value *DatabaseCreateSchedulesMetadataSync
	isSet bool
}

func (v NullableDatabaseCreateSchedulesMetadataSync) Get() *DatabaseCreateSchedulesMetadataSync {
	return v.value
}

func (v *NullableDatabaseCreateSchedulesMetadataSync) Set(val *DatabaseCreateSchedulesMetadataSync) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseCreateSchedulesMetadataSync) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseCreateSchedulesMetadataSync) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseCreateSchedulesMetadataSync(val *DatabaseCreateSchedulesMetadataSync) *NullableDatabaseCreateSchedulesMetadataSync {
	return &NullableDatabaseCreateSchedulesMetadataSync{value: val, isSet: true}
}

func (v NullableDatabaseCreateSchedulesMetadataSync) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseCreateSchedulesMetadataSync) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


