/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the SessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionRequest{}

// SessionRequest struct for SessionRequest
type SessionRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// NewSessionRequest instantiates a new SessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionRequest(username string, password string) *SessionRequest {
	this := SessionRequest{}
	this.Username = username
	this.Password = password
	return &this
}

// NewSessionRequestWithDefaults instantiates a new SessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionRequestWithDefaults() *SessionRequest {
	this := SessionRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *SessionRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *SessionRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *SessionRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *SessionRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SessionRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SessionRequest) SetPassword(v string) {
	o.Password = v
}

func (o SessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

type NullableSessionRequest struct {
	value *SessionRequest
	isSet bool
}

func (v NullableSessionRequest) Get() *SessionRequest {
	return v.value
}

func (v *NullableSessionRequest) Set(val *SessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionRequest(val *SessionRequest) *NullableSessionRequest {
	return &NullableSessionRequest{value: val, isSet: true}
}

func (v NullableSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
