/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the ListGroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGroups200Response{}

// ListGroups200Response struct for ListGroups200Response
type ListGroups200Response struct {
	Data []Group `json:"data,omitempty"`
}

// NewListGroups200Response instantiates a new ListGroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGroups200Response() *ListGroups200Response {
	this := ListGroups200Response{}
	return &this
}

// NewListGroups200ResponseWithDefaults instantiates a new ListGroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGroups200ResponseWithDefaults() *ListGroups200Response {
	this := ListGroups200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListGroups200Response) GetData() []Group {
	if o == nil || IsNil(o.Data) {
		var ret []Group
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroups200Response) GetDataOk() ([]Group, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListGroups200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Group and assigns it to the Data field.
func (o *ListGroups200Response) SetData(v []Group) {
	o.Data = v
}

func (o ListGroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListGroups200Response struct {
	value *ListGroups200Response
	isSet bool
}

func (v NullableListGroups200Response) Get() *ListGroups200Response {
	return v.value
}

func (v *NullableListGroups200Response) Set(val *ListGroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListGroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListGroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGroups200Response(val *ListGroups200Response) *NullableListGroups200Response {
	return &NullableListGroups200Response{value: val, isSet: true}
}

func (v NullableListGroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
