/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the DatabaseInputSchedules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseInputSchedules{}

// DatabaseInputSchedules struct for DatabaseInputSchedules
type DatabaseInputSchedules struct {
	MetadataSync *DatabaseInputSchedulesMetadataSync `json:"metadata_sync,omitempty"`
}

// NewDatabaseInputSchedules instantiates a new DatabaseInputSchedules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseInputSchedules() *DatabaseInputSchedules {
	this := DatabaseInputSchedules{}
	return &this
}

// NewDatabaseInputSchedulesWithDefaults instantiates a new DatabaseInputSchedules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseInputSchedulesWithDefaults() *DatabaseInputSchedules {
	this := DatabaseInputSchedules{}
	return &this
}

// GetMetadataSync returns the MetadataSync field value if set, zero value otherwise.
func (o *DatabaseInputSchedules) GetMetadataSync() DatabaseInputSchedulesMetadataSync {
	if o == nil || IsNil(o.MetadataSync) {
		var ret DatabaseInputSchedulesMetadataSync
		return ret
	}
	return *o.MetadataSync
}

// GetMetadataSyncOk returns a tuple with the MetadataSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseInputSchedules) GetMetadataSyncOk() (*DatabaseInputSchedulesMetadataSync, bool) {
	if o == nil || IsNil(o.MetadataSync) {
		return nil, false
	}
	return o.MetadataSync, true
}

// HasMetadataSync returns a boolean if a field has been set.
func (o *DatabaseInputSchedules) HasMetadataSync() bool {
	if o != nil && !IsNil(o.MetadataSync) {
		return true
	}

	return false
}

// SetMetadataSync gets a reference to the given DatabaseInputSchedulesMetadataSync and assigns it to the MetadataSync field.
func (o *DatabaseInputSchedules) SetMetadataSync(v DatabaseInputSchedulesMetadataSync) {
	o.MetadataSync = &v
}

func (o DatabaseInputSchedules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseInputSchedules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetadataSync) {
		toSerialize["metadata_sync"] = o.MetadataSync
	}
	return toSerialize, nil
}

type NullableDatabaseInputSchedules struct {
	value *DatabaseInputSchedules
	isSet bool
}

func (v NullableDatabaseInputSchedules) Get() *DatabaseInputSchedules {
	return v.value
}

func (v *NullableDatabaseInputSchedules) Set(val *DatabaseInputSchedules) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseInputSchedules) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseInputSchedules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseInputSchedules(val *DatabaseInputSchedules) *NullableDatabaseInputSchedules {
	return &NullableDatabaseInputSchedules{value: val, isSet: true}
}

func (v NullableDatabaseInputSchedules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseInputSchedules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


