/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the GroupCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupCreate{}

// GroupCreate struct for GroupCreate
type GroupCreate struct {
	Name string `json:"name"`
}

// NewGroupCreate instantiates a new GroupCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupCreate(name string) *GroupCreate {
	this := GroupCreate{}
	this.Name = name
	return &this
}

// NewGroupCreateWithDefaults instantiates a new GroupCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupCreateWithDefaults() *GroupCreate {
	this := GroupCreate{}
	return &this
}

// GetName returns the Name field value
func (o *GroupCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupCreate) SetName(v string) {
	o.Name = v
}

func (o GroupCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableGroupCreate struct {
	value *GroupCreate
	isSet bool
}

func (v NullableGroupCreate) Get() *GroupCreate {
	return v.value
}

func (v *NullableGroupCreate) Set(val *GroupCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupCreate(val *GroupCreate) *NullableGroupCreate {
	return &NullableGroupCreate{value: val, isSet: true}
}

func (v NullableGroupCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
