/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the DatabaseCreateSchedules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseCreateSchedules{}

// DatabaseCreateSchedules struct for DatabaseCreateSchedules
type DatabaseCreateSchedules struct {
	MetadataSync *DatabaseCreateSchedulesMetadataSync `json:"metadata_sync,omitempty"`
}

// NewDatabaseCreateSchedules instantiates a new DatabaseCreateSchedules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseCreateSchedules() *DatabaseCreateSchedules {
	this := DatabaseCreateSchedules{}
	return &this
}

// NewDatabaseCreateSchedulesWithDefaults instantiates a new DatabaseCreateSchedules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseCreateSchedulesWithDefaults() *DatabaseCreateSchedules {
	this := DatabaseCreateSchedules{}
	return &this
}

// GetMetadataSync returns the MetadataSync field value if set, zero value otherwise.
func (o *DatabaseCreateSchedules) GetMetadataSync() DatabaseCreateSchedulesMetadataSync {
	if o == nil || IsNil(o.MetadataSync) {
		var ret DatabaseCreateSchedulesMetadataSync
		return ret
	}
	return *o.MetadataSync
}

// GetMetadataSyncOk returns a tuple with the MetadataSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseCreateSchedules) GetMetadataSyncOk() (*DatabaseCreateSchedulesMetadataSync, bool) {
	if o == nil || IsNil(o.MetadataSync) {
		return nil, false
	}
	return o.MetadataSync, true
}

// HasMetadataSync returns a boolean if a field has been set.
func (o *DatabaseCreateSchedules) HasMetadataSync() bool {
	if o != nil && !IsNil(o.MetadataSync) {
		return true
	}

	return false
}

// SetMetadataSync gets a reference to the given DatabaseCreateSchedulesMetadataSync and assigns it to the MetadataSync field.
func (o *DatabaseCreateSchedules) SetMetadataSync(v DatabaseCreateSchedulesMetadataSync) {
	o.MetadataSync = &v
}

func (o DatabaseCreateSchedules) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseCreateSchedules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetadataSync) {
		toSerialize["metadata_sync"] = o.MetadataSync
	}
	return toSerialize, nil
}

type NullableDatabaseCreateSchedules struct {
	value *DatabaseCreateSchedules
	isSet bool
}

func (v NullableDatabaseCreateSchedules) Get() *DatabaseCreateSchedules {
	return v.value
}

func (v *NullableDatabaseCreateSchedules) Set(val *DatabaseCreateSchedules) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseCreateSchedules) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseCreateSchedules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseCreateSchedules(val *DatabaseCreateSchedules) *NullableDatabaseCreateSchedules {
	return &NullableDatabaseCreateSchedules{value: val, isSet: true}
}

func (v NullableDatabaseCreateSchedules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseCreateSchedules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
