/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the SessionCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionCreate{}

// SessionCreate struct for SessionCreate
type SessionCreate struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// NewSessionCreate instantiates a new SessionCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionCreate(username string, password string) *SessionCreate {
	this := SessionCreate{}
	this.Username = username
	this.Password = password
	return &this
}

// NewSessionCreateWithDefaults instantiates a new SessionCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionCreateWithDefaults() *SessionCreate {
	this := SessionCreate{}
	return &this
}

// GetUsername returns the Username field value
func (o *SessionCreate) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *SessionCreate) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *SessionCreate) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *SessionCreate) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SessionCreate) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SessionCreate) SetPassword(v string) {
	o.Password = v
}

func (o SessionCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

type NullableSessionCreate struct {
	value *SessionCreate
	isSet bool
}

func (v NullableSessionCreate) Get() *SessionCreate {
	return v.value
}

func (v *NullableSessionCreate) Set(val *SessionCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionCreate(val *SessionCreate) *NullableSessionCreate {
	return &NullableSessionCreate{value: val, isSet: true}
}

func (v NullableSessionCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


