/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the SessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionResponse{}

// SessionResponse struct for SessionResponse
type SessionResponse struct {
	Id *string `json:"id,omitempty"`
}

// NewSessionResponse instantiates a new SessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionResponse() *SessionResponse {
	this := SessionResponse{}
	return &this
}

// NewSessionResponseWithDefaults instantiates a new SessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionResponseWithDefaults() *SessionResponse {
	this := SessionResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SessionResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SessionResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SessionResponse) SetId(v string) {
	o.Id = &v
}

func (o SessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableSessionResponse struct {
	value *SessionResponse
	isSet bool
}

func (v NullableSessionResponse) Get() *SessionResponse {
	return v.value
}

func (v *NullableSessionResponse) Set(val *SessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionResponse(val *SessionResponse) *NullableSessionResponse {
	return &NullableSessionResponse{value: val, isSet: true}
}

func (v NullableSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


