/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gometabase

import (
	"encoding/json"
)

// checks if the DatabaseInputSchedulesMetadataSync type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseInputSchedulesMetadataSync{}

// DatabaseInputSchedulesMetadataSync struct for DatabaseInputSchedulesMetadataSync
type DatabaseInputSchedulesMetadataSync struct {
	ScheduleType *string `json:"schedule_type,omitempty"`
}

// NewDatabaseInputSchedulesMetadataSync instantiates a new DatabaseInputSchedulesMetadataSync object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseInputSchedulesMetadataSync() *DatabaseInputSchedulesMetadataSync {
	this := DatabaseInputSchedulesMetadataSync{}
	return &this
}

// NewDatabaseInputSchedulesMetadataSyncWithDefaults instantiates a new DatabaseInputSchedulesMetadataSync object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseInputSchedulesMetadataSyncWithDefaults() *DatabaseInputSchedulesMetadataSync {
	this := DatabaseInputSchedulesMetadataSync{}
	return &this
}

// GetScheduleType returns the ScheduleType field value if set, zero value otherwise.
func (o *DatabaseInputSchedulesMetadataSync) GetScheduleType() string {
	if o == nil || IsNil(o.ScheduleType) {
		var ret string
		return ret
	}
	return *o.ScheduleType
}

// GetScheduleTypeOk returns a tuple with the ScheduleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseInputSchedulesMetadataSync) GetScheduleTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduleType) {
		return nil, false
	}
	return o.ScheduleType, true
}

// HasScheduleType returns a boolean if a field has been set.
func (o *DatabaseInputSchedulesMetadataSync) HasScheduleType() bool {
	if o != nil && !IsNil(o.ScheduleType) {
		return true
	}

	return false
}

// SetScheduleType gets a reference to the given string and assigns it to the ScheduleType field.
func (o *DatabaseInputSchedulesMetadataSync) SetScheduleType(v string) {
	o.ScheduleType = &v
}

func (o DatabaseInputSchedulesMetadataSync) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseInputSchedulesMetadataSync) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScheduleType) {
		toSerialize["schedule_type"] = o.ScheduleType
	}
	return toSerialize, nil
}

type NullableDatabaseInputSchedulesMetadataSync struct {
	value *DatabaseInputSchedulesMetadataSync
	isSet bool
}

func (v NullableDatabaseInputSchedulesMetadataSync) Get() *DatabaseInputSchedulesMetadataSync {
	return v.value
}

func (v *NullableDatabaseInputSchedulesMetadataSync) Set(val *DatabaseInputSchedulesMetadataSync) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseInputSchedulesMetadataSync) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseInputSchedulesMetadataSync) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseInputSchedulesMetadataSync(val *DatabaseInputSchedulesMetadataSync) *NullableDatabaseInputSchedulesMetadataSync {
	return &NullableDatabaseInputSchedulesMetadataSync{value: val, isSet: true}
}

func (v NullableDatabaseInputSchedulesMetadataSync) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseInputSchedulesMetadataSync) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


